repos:
-   repo: https://github.com/pycqa/flake8
    rev: '4.0.1'
    hooks:
    -   id: flake8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.910-1'
    hooks:
    -   id: mypy
-   repo: https://github.com/s-weigand/flake8-nb
    rev: 'v0.3.1'
    hooks:
    - id: flake8-nb